<?php declare(strict_types=1); ?>
<section class="page-hero legal-hero">
    <div class="container page-hero-grid">
        <div data-reveal><p class="eyebrow">Privacy</p><h1>A clear approach to <em>your information.</em></h1></div>
        <p data-reveal>This notice explains what this website collects through inquiry and pickup-sheet forms, how optional analytics works, and how that information is used.</p>
    </div>
</section>

<section class="section legal-page">
    <div class="container legal-grid">
        <aside><p class="eyebrow">Last updated</p><strong>29 August 2026</strong></aside>
        <div class="legal-copy">
            <article><h2>Data controller</h2><p>T&amp;Tech Consulting Group, headquartered in Cameroon with locations in Bamenda and Douala, controls the personal information submitted through this website. Privacy requests may be sent to info@ttechcg.com.</p></article>
            <article><h2>Information we collect</h2><p>When you use the inquiry form, we collect the name, email address, company, service interest, and message you provide. When you use Pickupsheet, we collect the agent name, collection date, consignor, AWB number, destination, cash amount, piece count, weight, and the checker identity associated with the authenticated account. The server records the collection time automatically when the pickup sheet is submitted. For staff access, we store the assigned first name, last name, email address or username, role, Active/Inactive status, one-way password hash, identity-provider source, and pseudonymous administrator audit identifier; plaintext passwords are not stored. We record successful staff login, last-activity, and logout times so administrators can review login frequency, active sessions, and session duration. When JumpCloud SSO is enabled, JumpCloud supplies a stable subject identifier, verified email, first and last name, and group membership used to assign the Pickupsheet role. Access and ID tokens are used only to complete sign-in and are not retained in the application session or database. Record edits retain pseudonymous actor details and before-and-after snapshots. Paid-status changes and administrative deletions also retain pseudonymous audit details. We also record when you opted in and the version of this privacy notice presented with the form. The web server may retain standard technical logs used for security and reliability.</p></article>
            <article><h2>How we use it</h2><p>We use inquiry information to understand your request, respond to you, and manage the resulting business conversation. Pickup-sheet information is used to record and reconcile cash shipment collections and their operational handoff. We do not sell inquiry information. We do not sell pickup-sheet information.</p></article>
            <article><h2>Your consent</h2><p>The inquiry and pickup-sheet forms require an explicit, unchecked opt-in before submission. You may withdraw that consent by emailing info@ttechcg.com. Withdrawal does not affect processing that occurred lawfully before your request, and we may retain records where another legal obligation requires it.</p></article>
            <article><h2>Essential session cookie</h2><p>This site uses one first-party session cookie to authenticate Pickupsheet staff, enforce role permissions, protect forms, retain the CAPTCHA challenge, display submission status, and prevent abuse. The cookie is necessary for the requested functionality, expires with the browser session, and is not used for advertising or cross-site tracking.</p></article>
            <article><h2>JumpCloud single sign-on</h2><p>Authorised staff may sign in through JumpCloud. The browser is redirected to JumpCloud for authentication and any configured multifactor challenge, then returned to this site. Pickupsheet verifies JumpCloudâ€™s signed response and uses approved group membership to assign viewer, operator, or administrator access. Passwords and multifactor credentials entered at JumpCloud are not received by this site. JumpCloudâ€™s processing is governed by its <a href="https://jumpcloud.com/privacy" target="_blank" rel="noopener">privacy notice</a>.</p></article>
            <article><h2>Cloudflare Access handoff</h2><p>When Pickupsheet is protected by Cloudflare Access, Cloudflare may pass a signed application token after JumpCloud has authenticated the staff member. Pickupsheet verifies the token and retrieves the full Access identity to confirm the email address, display name, and approved JumpCloud group used for role assignment. The Access token is used only to complete the handoff and is not retained in the application session or database. Cloudflareâ€™s processing is governed by its <a href="https://www.cloudflare.com/privacypolicy/" target="_blank" rel="noopener">privacy policy</a>.</p></article>
            <article><h2>Optional Google Analytics</h2><p>This site includes the Google tag with measurement ID G-WVFXFB5H3M on each page. Consent Mode initially denies analytics and advertising storage, so Google Analytics cookies such as <code>_ga</code> are not permitted unless you choose “Accept analytics.” Before acceptance, Google may receive cookieless consent-state pings; accepting enables analytics storage so we can understand page usage, device and browser characteristics, approximate location, and site performance. Declining keeps analytics storage denied. Analytics page views are suppressed on pickup-sheet operational pages, and record-reference query values are removed from the tag configuration.</p><p>You can change your choice at any time with the “Cookie settings” control in the footer. Advertising storage, advertising user data, and ad personalisation remain disabled. Learn more in <a href="https://policies.google.com/privacy" target="_blank" rel="noopener">Google’s Privacy Policy</a>.</p></article>
            <article><h2>Storage and access</h2><p>Inquiry and pickup-sheet information is stored in the website’s database. Inquiry information is also forwarded by email to info@ttechcg.com so the T&amp;Tech team can respond. Every Pickupsheet screen requires an authorised staff login. Viewers and operators can create and view records; operators and administrators can print PDFs and export Excel files. Only administrators can edit records, change an open sheet to paid, remove a sheet from active views through an audited soft deletion, or manage user access. Access is limited to people who need it to respond, reconcile shipments, or operate the service.</p></article>
            <article><h2>Retention</h2><p>We retain inquiry and pickup-sheet information only for as long as it remains useful for the conversation, operational reconciliation, legitimate business records, security, or applicable legal obligations.</p></article>
            <article><h2>Your choices</h2><p>You may ask T&amp;Tech to access, correct, or delete information you submitted, or to restrict or object to its processing, subject to applicable legal and record-keeping obligations. Email info@ttechcg.com to make a privacy request.</p></article>
            <article><h2>Changes to this notice</h2><p>We may update this notice when the website or its information practices change. The effective date above identifies the current version.</p></article>
            <a class="button button-primary" href="<?= htmlspecialchars($basePath . '/contact', ENT_QUOTES, 'UTF-8') ?>">Contact T&amp;Tech <span aria-hidden="true">↗</span></a>
        </div>
    </div>
</section>
