<?php declare(strict_types=1); ?>
<dialog class="pickup-privacy-dialog" id="pickupsheet-privacy" aria-labelledby="pickupsheet-privacy-title" data-privacy-dialog>
    <header>
        <div>
            <p>Pickupsheet privacy notice</p>
            <h2 id="pickupsheet-privacy-title">How Pickupsheet handles your information</h2>
            <small>Last updated 3 October 2026</small>
        </div>
        <button class="pickup-privacy-close" type="button" data-privacy-dialog-close aria-label="Close privacy notice">&times;</button>
    </header>
    <div class="pickup-privacy-copy">
        <section><h3>Scope</h3><p>This notice covers Pickupsheet, the staff-only T&amp;Tech portal used to record DHL cash pickup collections, manage the customer directory, and administer staff access. The public ttechcg.com website, including its inquiry form, is covered by a separate <a href="<?= $e($url('/privacy')) ?>" target="_blank" rel="noopener">website privacy notice</a>.</p></section>
        <section><h3>Data controller</h3><p>T&amp;Tech Consulting Group, headquartered in Cameroon with locations in Bamenda and Douala, controls the personal information processed in Pickupsheet. Privacy requests may be sent to info@ttechcg.com.</p></section>
        <section><h3>Information we collect</h3><p>Pickup sheets record the agent name, collection date, consignor, AWB number, destination, cash amount, piece count, weight, and the checker identity associated with the authenticated account. The server records the collection time automatically when the pickup sheet is submitted. Shipment consignor names are synchronized into the restricted customer directory. Administrators may create profiles and set customer, organization, and contact names. Operators and administrators may maintain business email, Cameroon phone number, address, city, relationship status, internal notes, and a follow-up date; the directory adds the Cameroon +237 calling code to local phone numbers and calculates shipment frequency, value, and first and last shipment dates. Every customer profile is assigned to the administrator role. Customer reward points are calculated from recorded cargo weight at 10 points per kilogram shipped. Manual reward bonuses and redemptions retain the point change, required reason, UTC time, and pseudonymous administrator identifier.</p><p>For staff access, we store the assigned first name, last name, email address or username, role, Active/Inactive status, one-way password hash, identity-provider source, and pseudonymous administrator audit identifier; plaintext passwords are not stored. We record successful staff login, last-activity, and logout times so administrators can review login frequency, active sessions, and session duration. Detailed Pickupsheet logs retain the event action, result, protected route, request identifier, and pseudonymous client identifier, plus hashed actor, target, and record identifiers where relevant; they do not retain passwords, form contents, raw record references, or raw IP addresses. Record edits retain pseudonymous actor details and before-and-after snapshots. Paid-status changes and administrative deletions also retain pseudonymous audit details. We also record when you opted in and the version of this privacy notice presented with the pickup-sheet form. The web server may retain standard technical logs used for security and reliability.</p></section>
        <section><h3>How we use it</h3><p>Pickup-sheet information is used to record and reconcile cash shipment collections and their operational handoff. Customer-directory information is used to manage service relationships, preserve relevant shipment context, schedule follow-up, and operate the shipment reward programme. CRM profile access is limited to Pickupsheet operators and administrators; profile creation, name changes, and manual reward controls remain limited to administrators. Local-account authenticator secrets are encrypted at rest, recovery codes are stored only as keyed hashes, and verification events are security-logged without recording a code. Administrators may create passphrase-encrypted backups containing application records, local account password hashes, encrypted authenticator enrollments, and recovery-code hashes for disaster recovery; environment secrets and plaintext passwords are excluded. We do not sell pickup-sheet or customer-directory information.</p></section>
        <section><h3>Your consent</h3><p>The pickup-sheet form requires an explicit, unchecked opt-in before submission. You may withdraw that consent by emailing info@ttechcg.com. Withdrawal does not affect processing that occurred lawfully before your request, and we may retain records where another legal obligation requires it.</p></section>
        <section><h3>Essential session cookie</h3><p>Pickupsheet uses one first-party session cookie to authenticate staff, enforce role permissions, protect forms, retain the CAPTCHA challenge, display submission status, and prevent abuse. The cookie is necessary for the requested functionality, expires with the browser session, and is not used for advertising or cross-site tracking.</p></section>
        <section><h3>JumpCloud single sign-on</h3><p>Authorised staff may sign in through JumpCloud. The browser is redirected to JumpCloud for authentication and any configured multifactor challenge, then returned to Pickupsheet. Pickupsheet verifies JumpCloud’s signed response and uses its stable subject identifier, verified email, first and last name, and approved group membership to assign viewer, operator, or administrator access. Passwords and multifactor credentials entered at JumpCloud are not received by Pickupsheet. Access and ID tokens are used only to complete sign-in and are not retained in the application session or database. JumpCloud’s processing is governed by its <a href="https://jumpcloud.com/privacy" target="_blank" rel="noopener">privacy notice</a>.</p></section>
        <section><h3>Cloudflare Access handoff</h3><p>When Pickupsheet is protected by Cloudflare Access, Cloudflare may pass a signed application token after JumpCloud has authenticated the staff member. Pickupsheet verifies the token and retrieves the full Access identity to confirm the email address, display name, and approved JumpCloud group used for role assignment. The Access token is used only to complete the handoff and is not retained in the application session or database. Cloudflare’s processing is governed by its <a href="https://www.cloudflare.com/privacypolicy/" target="_blank" rel="noopener">privacy policy</a>.</p></section>
        <section><h3>Analytics</h3><p>Pickupsheet pages load the Google tag in Consent Mode with analytics and advertising storage denied by default. Analytics page views are suppressed on pickup-sheet operational pages, and record-reference query values are removed from the tag configuration. Advertising storage, advertising user data, and ad personalisation remain disabled.</p></section>
        <section><h3>Storage and access</h3><p>Pickup-sheet, customer-directory, and reward-ledger information is stored in the Pickupsheet database. Every Pickupsheet screen requires an authorised staff login. Viewers and operators can create and view records; operators and administrators can print PDFs and export Excel files. Operators and administrators can view customer profiles and update profile details, but operators cannot change customer, organization, or contact names. Only administrators can create customer profiles, change names, adjust rewards, edit pickup records, change an open sheet to paid, remove a sheet from active views through an audited soft deletion, or manage user access. Access is limited to people who need it to reconcile shipments, manage customer relationships, or operate the service.</p></section>
        <section><h3>Retention</h3><p>We retain pickup-sheet, customer-directory, reward-ledger, account, and audit information only for as long as it remains useful for operational reconciliation, the customer relationship, legitimate business records, security, or applicable legal obligations.</p></section>
        <section><h3>Your choices</h3><p>You may ask T&amp;Tech to access, correct, or delete information held in Pickupsheet, or to restrict or object to its processing, subject to applicable legal and record-keeping obligations. Email info@ttechcg.com to make a privacy request.</p></section>
        <section><h3>Changes to this notice</h3><p>We may update this notice when Pickupsheet or its information practices change. The date above identifies the current version.</p></section>
    </div>
    <footer class="pickup-privacy-actions">
        <button type="button" data-privacy-dialog-close>Close</button>
    </footer>
</dialog>
